VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end

  # Ansible demo server 1
  config.vm.define "ansibledemo" do |ansdemo|
    ansdemo.vm.hostname = "ansibledemo.dev"
    ansdemo.vm.box = "ubuntu/trusty64"
    ansdemo.vm.network :private_network, ip: "192.168.60.11"
    ansdemo.vm.network "forwarded_port", guest: 80, host: 8000
    ansdemo.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.inventory_path = "hosts"
      ansible.limit = "all"
    end
  end
end
